// Generated by CoffeeScript 1.8.0
var Ducke, Modem, demux, groupimages, parallel, stream, tardir,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Modem = require('./modem');

demux = require('./demuxstream');

tardir = require('./tardir');

groupimages = require('./groupimages');

stream = require('stream');

parallel = function(tasks, callback) {
  var count, result;
  count = tasks.length;
  result = function(cb) {
    var task, _i, _len, _results;
    if (count === 0) {
      return cb();
    }
    _results = [];
    for (_i = 0, _len = tasks.length; _i < _len; _i++) {
      task = tasks[_i];
      _results.push(task(function() {
        count--;
        if (count === 0) {
          return cb();
        }
      }));
    }
    return _results;
  };
  if (callback != null) {
    result(callback);
  }
  return result;
};

module.exports = Ducke = (function() {
  function Ducke(options) {
    this.image = __bind(this.image, this);
    this.build_image = __bind(this.build_image, this);
    this.container = __bind(this.container, this);
    this.createContainer = __bind(this.createContainer, this);
    this.ls = __bind(this.ls, this);
    this.ps = __bind(this.ps, this);
    this.ping = __bind(this.ping, this);
    this._modem = new Modem(options);
  }

  Ducke.prototype.ping = function(callback) {
    return this._modem.get('/_ping').result(function(err, result) {
      if (err != null) {
        return callback(err);
      }
      return callback(null, result === 'OK');
    });
  };

  Ducke.prototype.ps = function(callback) {
    return this._modem.get('/containers/json?all=1').result((function(_this) {
      return function(err, containers) {
        var container, errors, statuses, tasks, _fn, _i, _len;
        if (err != null) {
          return callback(err);
        }
        statuses = [];
        errors = [];
        tasks = [];
        _fn = function(container) {
          return tasks.push(function(cb) {
            return _this._modem.get("/containers/" + container.Id + "/json").result(function(err, inspect) {
              if (err != null) {
                errors.push(err);
                return cb();
              }
              statuses.push({
                container: container,
                inspect: inspect
              });
              return cb();
            });
          });
        };
        for (_i = 0, _len = containers.length; _i < _len; _i++) {
          container = containers[_i];
          _fn(container);
        }
        return parallel(tasks, function() {
          statuses.sort(function(a, b) {
            a = a.container.Names[0];
            b = b.container.Names[0];
            if (a > b) {
              return 1;
            }
            if (a < b) {
              return -1;
            }
            return 0;
          });
          if (errors.length > 0) {
            return callback(errors, statuses);
          }
          return callback(null, statuses);
        });
      };
    })(this));
  };

  Ducke.prototype.ls = function(callback) {
    return this._modem.get('/images/json?all=1').result((function(_this) {
      return function(err, images) {
        if (err != null) {
          return callback(err);
        }
        return callback(null, groupimages(images));
      };
    })(this));
  };

  Ducke.prototype.createContainer = function(name, params, callback) {
    var url;
    url = '/containers/create';
    if (name != null) {
      url += "?name=" + name;
    }
    return this._modem.post(url, params).result(callback);
  };

  Ducke.prototype.container = function(id) {
    return {
      inspect: (function(_this) {
        return function(callback) {
          return _this._modem.get("/containers/" + id + "/json").result(callback);
        };
      })(this),
      logs: (function(_this) {
        return function(callback) {
          return _this._modem.get("/containers/" + id + "/logs?stderr=1&stdout=1&follow=1&tail=10").stream(callback);
        };
      })(this),
      resize: (function(_this) {
        return function(rows, columns, callback) {
          return _this._modem.get("/containers/" + id + "/resize?h=" + rows + "&w=" + columns).result(function(err, result) {
            if (err != null) {
              return callback(err);
            }
            return callback(null, result === 'OK');
          });
        };
      })(this),
      start: (function(_this) {
        return function(callback) {
          return _this._modem.post("/containers/" + id + "/start", {}).result(callback);
        };
      })(this),
      stop: (function(_this) {
        return function(callback) {
          return _this._modem.post("/containers/" + id + "/stop?t=5", {}).result(callback);
        };
      })(this),
      wait: (function(_this) {
        return function(callback) {
          return _this._modem.post("/containers/" + id + "/wait", {}).result(callback);
        };
      })(this),
      rm: (function(_this) {
        return function(callback) {
          return _this._modem["delete"]("/containers/" + id).result(callback);
        };
      })(this),
      attach: (function(_this) {
        return function(callback) {
          return _this._modem.post("/containers/" + id + "/attach?stream=true&stdin=true&stdout=true&stderr=true", {}).connect(callback);
        };
      })(this),
      kill: (function(_this) {
        return function(callback) {
          return _this._modem.post("/containers/" + id + "/kill?signal=SIGTERM", {}).result(callback);
        };
      })(this),
      exec: (function(_this) {
        return function(cmd, stdin, stdout, stderr, callback) {
          var params;
          params = {
            AttachStdin: true,
            AttachStdout: true,
            AttachStderr: true,
            Tty: true,
            Cmd: cmd
          };
          return _this._modem.post("/containers/" + id + "/exec", params).result(function(err, exec) {
            if (err != null) {
              return callback(err);
            }
            return _this._modem.post("/exec/" + exec.Id + "/start", {
              Detach: false,
              Tty: true
            }).connect(function(err, stream) {
              var wasRaw;
              if (err != null) {
                return callback(err);
              }
              stream.pipe(stdout);
              wasRaw = process.isRaw;
              stdin.resume();
              stdin.setEncoding('utf8');
              stdin.setRawMode(true);
              stdin.pipe(stream);
              return stream.on('end', function() {
                stdin.removeAllListeners();
                stdin.setRawMode(wasRaw);
                stdin.resume();
                return callback(null, 0);
              });
            });
          });
        };
      })(this)
    };
  };

  Ducke.prototype.build_image = function(id, path, usecache, run, callback) {
    return tardir(path, (function(_this) {
      return function(err, archive) {
        var cache;
        if (err != null) {
          return callback(err);
        }
        archive.on('error', callback);
        cache = '';
        if (!usecache) {
          cache = '&nocache=true';
        }
        return _this._modem.postFile("/build?t=" + id + cache, archive).stream(function(err, output) {
          if (err != null) {
            return callback(err);
          }
          output.on('data', function(data) {
            var line, lines, _i, _len, _results;
            data = JSON.parse(data);
            if (data.error != null) {
              return callback(data.error);
            }
            lines = data.stream.split('\n').filter(function(d) {
              return d !== '';
            });
            _results = [];
            for (_i = 0, _len = lines.length; _i < _len; _i++) {
              line = lines[_i];
              _results.push(run(line));
            }
            return _results;
          });
          return output.on('end', callback);
        });
      };
    })(this));
  };

  Ducke.prototype.image = function(id) {
    return {
      rebuild: (function(_this) {
        return function(path, run, callback) {
          return _this.build_image(id, path, false, run, callback);
        };
      })(this),
      build: (function(_this) {
        return function(path, run, callback) {
          return _this.build_image(id, path, true, run, callback);
        };
      })(this),
      up: (function(_this) {
        return function(name, cmd, callback) {
          var params;
          params = {
            Image: id
          };
          if (cmd.length > 0) {
            params.Cmd = cmd;
          }
          return _this.createContainer(name, params, function(err, container) {
            if (err != null) {
              return callback(err);
            }
            id = container.Id;
            container = _this.container(id);
            return container.start(function(err) {
              if (err != null) {
                return callback(err);
              }
              return callback(null, id);
            });
          });
        };
      })(this),
      inspect: (function(_this) {
        return function(callback) {
          return _this._modem.get("/images/" + id + "/json").result(callback);
        };
      })(this),
      rm: (function(_this) {
        return function(callback) {
          return _this._modem["delete"]("/images/" + id).result(callback);
        };
      })(this),
      run: (function(_this) {
        return function(cmd, stdin, stdout, stderr, run, callback) {
          var params;
          params = {
            AttachStdin: true,
            AttachStdout: true,
            AttachStderr: true,
            Tty: true,
            OpenStdin: true,
            StdinOnce: false,
            Cmd: cmd,
            Image: id
          };
          return _this.createContainer(null, params, function(err, container) {
            if (err != null) {
              return run(err);
            }
            id = container.Id;
            container = _this.container(container.Id);
            return container.attach(function(err, stream) {
              var wasRaw;
              if (err != null) {
                return run(err);
              }
              run(null, id);
              stream.pipe(stdout);
              wasRaw = process.isRaw;
              stdin.resume();
              stdin.setEncoding('utf8');
              stdin.setRawMode(true);
              stdin.pipe(stream);
              return container.start(function(err) {
                var kill;
                if (err != null) {
                  return callback(err);
                }
                kill = function(signal) {
                  stream.unpipe(stdout);
                  stdin.unpipe(stream);
                  stream.end();
                  return container.kill(function() {});
                };
                process.on('SIGTERM', function() {
                  return kill('SIGTERM');
                });
                process.on('SIGINT', function() {
                  return kill('SIGINT');
                });
                process.on('SIGHUP', function() {
                  return kill('SIGHUP');
                });
                process.on('uncaughtException', function(err) {
                  log(err.stack);
                  return process.exit(1);
                });
                return container.wait(function(err, result) {
                  if (err != null) {
                    return callback(err);
                  }
                  return container.rm(function(err) {
                    if (err != null) {
                      return callback(err);
                    }
                    return callback(null, result.StatusCode);
                  });
                });
              });
            });
          });
        };
      })(this)
    };
  };

  return Ducke;

})();
