// Generated by CoffeeScript 1.8.0
var fs, tar, zlib;

fs = require('fs');

tar = require('tar-fs');

zlib = require('zlib');

module.exports = function(path, cb) {
  var output;
  if (!fs.existsSync(path)) {
    return cb(new Error("" + path + " not found"));
  }
  if (!fs.lstatSync(path).isDirectory()) {
    return cb(new Error("" + path + " is not a directory"));
  }
  output = tar.pack(path).pipe(zlib.createGzip());
  return cb(null, output);
};
